### ISSUE TITLE
Credential helper support in kaniko build 

### ISSUE THREAD

**Issue by mchmarny** [knative/build-templates#32]

**Comment by jchesterpivotal** [comment]
... just ran smack into this one :|

**Comment by mattmoor** [comment]
I think kaniko needs to release?

**Comment by ImJasonH** [comment]
https://gcr.io/kaniko-project/executor claims the image was released 2 hours ago, and has many builds since that PR was merged.

/cc @priyawadhwa

**Comment by mattmoor** [comment]
https://github.com/GoogleContainerTools/kaniko/tree/v0.1.0 ?

**Comment by priyawadhwa** [comment]
It looks like `gcr.io/kaniko-project/executor:latest` isn't the same as when I build it locally @ HEAD

We use build triggers to deploy the image, and I think something went wrong there because the commit tagged version of the image `gcr.io/kaniko-project/executor:8f71b7fb260cd08f1acd9b7854df9a82a444382c` is correct, but `gcr.io/kaniko-project/executor:latest`, which is built via 
```
docker tag gcr.io/kaniko-project/executor:8f71b7fb260cd08f1acd9b7854df9a82a444382c gcr.io/kaniko-project/executor:latest
```

 is different.

I reran the trigger and they seem to be the same now, so hopefully that should fix this issue. Unfortunately I'm not sure why it happened :(

**Comment by jchesterpivotal** [comment]
Still seeing this behaviour. I may be looking at [a different bug](https://github.com/GoogleContainerTools/kaniko/issues/245) on Kaniko though.

**Comment by priyawadhwa** [comment]
@jchesterpivotal , could you comment on that issue with more some more information? The error you're seeing and the Dockerfile you're trying to build would be really helpful.
